name: $(version).$(rev:r)

trigger: none

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  displayName: .NET Restore
  inputs:
    command: 'restore'
    
- task: DotNetCoreCLI@2
  displayName: .NET Test
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: .NET Pack
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    configuration: 'release'
    buildProperties: 'Version=$(Build.BuildNumber);'

- task: NuGetCommand@2
  displayName: .NET Push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'
